# Generated by Django 3.0.5 on 2023-04-05 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20230319_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('Mark', models.CharField(max_length=50)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTestMark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('sample', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('notes_title', models.CharField(max_length=100)),
                ('regulation', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='notes/')),
            ],
        ),
        migrations.AddField(
            model_name='attendees',
            name='roll_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_enrolled',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='URLForClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Class_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='ebooks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.NoteCourse')),
            ],
        ),
        migrations.CreateModel(
            name='EbookForClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cover_image', models.CharField(max_length=100)),
                ('Class_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='ebooks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.NoteCourse')),
            ],
        ),
    ]
