# Generated by Django 3.0.5 on 2023-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_test_mark',
            name='sample',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
