# Generated by Django 3.0.5 on 2023-04-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_daily_test_mark_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_test_mark',
            new_name='DailyTestMark',
        ),
    ]
