# Generated by Django 3.0.5 on 2023-04-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20230405_1935'),
        ('base', '0040_auto_20230405_1933'),
    ]

    operations = [
    ]
